-- 1.
SET AUTOCOMMIT = 0;
START TRANSACTION;
 ALTER TABLE gost
 ADD dodata_kolona varchar(20) NOT NULL;
COMMIT;
SET AUTOCOMMIT = 1;

-- 2.
SET AUTOCOMMIT = 0;
START TRANSACTION;
 ALTER TABLE gost
 DROP COLUMN dodata_kolona;
COMMIT;
SET AUTOCOMMIT = 1;
-- 3.
SET AUTOCOMMIT = 0;
START TRANSACTION;
 UPDATE gost
 SET ime = 'Novo Ime'
 WHERE ime = 'Ime';
COMMIT;
SET AUTOCOMMIT = 1;
-- 4.
SET AUTOCOMMIT = 0;
START TRANSACTION;
SAVEPOINT save;
 UPDATE gost
 SET ime = 'Novo Ime'
 WHERE ime = 'Ime';
ROLLBACK;
SET AUTOCOMMIT = 1;
-- 5.
SET AUTOCOMMIT = 0;
START TRANSACTION;
SAVEPOINT save;
 UPDATE soba
 SET opis = 'Nova Soba'
 WHERE broj = 1;
ROLLBACK;


